In [1]:
import tensorflow as tf

In [2]:
# tape with tensor operations on a scalar value
x = tf.Variable(25.)
with tf.GradientTape() as tape:
    y = 2*x + 3
    
print(tape.gradient(y, x))

tf.Tensor(2.0, shape=(), dtype=float32)


In [3]:
# tape with tensor operations on a matrix
x = tf.Variable(tf.random.normal((5, 5), mean = 1, stddev= 5))
with tf.GradientTape() as tape:
    y = 2*x + 3

print(tape.gradient(y, x))

tf.Tensor(
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]], shape=(5, 5), dtype=float32)


In [4]:
# tape with tensor operations on multiple variables
W = tf.Variable(tf.random.uniform((2, 2), minval=-5, maxval=5))
b = tf.Variable(tf.random.uniform((2,)))
x = tf.random.uniform((2, 2))
with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b
    z = tf.nn.relu(y)

print(tape.gradient(z, [W, b]))

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.68603516, 0.68603516],
       [0.8935547 , 0.8935547 ]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>]
